### ISSUE TITLE
Old version of SDL

### ISSUE THREAD

**Issue by baronleonardo** [slowbrowser/slowbrowser#11]
you are using the older version of SDL you need to use SDL2 instead (SDL is obsolete)

**Comment by lordadamson** [comment]
turns out it's already sdl2

**Comment by baronleonardo** [comment]
as far as I know SDL should be included like this `#include <SDL2/SDL.h>`

**Comment by lordadamson** [comment]
depends on whether you added SDL2/ to your include paths or not, which I did.
Maybe I should have the headers moved inside an SDL2 directory to be compatible with your include paths

**Comment by baronleonardo** [comment]
ooooooooh I almost forget you include headers from in-project folder .. no problem then :D
